### ISSUE TITLE
用了这个字典以后，phones依然显示spn

### ISSUE THREAD

**Issue by caolusg** [GalaxieT/MFA-mandarin-pinyin-dict-for-pretrained-mfa-model-v2.0#2]
请问你的是正常的吗

**Comment by GalaxieT** [comment]
我的是正常的，请问输入的是由空格分开的拼音文本吗，格式类似“a1 ba2 de6”这样子的

**Comment by caolusg** [comment]
正常了。你感觉MFA精度怎样？我想联合EEG分析。但是声母的跨度好像只有0.01秒级别。这么短，适合分析吗？

**Comment by GalaxieT** [comment]
感觉一般，但是暂时找不到更好的。直接用在eeg上可能稍差，考虑在自动标注的基础上手动修正？

**Comment by caolusg** [comment]
是的，目前自动标注了一遍以后，正在做人工的修正。有人使用eeg去分析音素级别的发音吗？这条路，理论和实践上可行吗？我也是刚接触这个话题。还不了解常用的思路的研究手法。

**Comment by GalaxieT** [comment]
不太清楚，应该是有的，可以找找相关论文
