### ISSUE TITLE
有相关拼音到IPA的映射参考吗

### ISSUE THREAD

**Issue by ABC0408** [GalaxieT/MFA-mandarin-pinyin-dict-for-pretrained-mfa-model-v2.0#3]
对IPA音标不了解，看到同一个拼音也有不同的映射，可以指点一下吗？
1. 
[zuo1: tsuɔ˥˥](https://github.com/kfcd/pinyin/blob/master/pinyinbiao)
[zuo1: ts w o˥˥](https://github.com/GalaxieT/MFA-mandarin-pinyin-dict-for-pretrained-mfa-model-v2.0/blob/main/mandarin_pinyin_to_mfa_lty.dict)
2. 想问一下mandarin_mfa.dict 里面的：<'unk'>	0.99	0.33	2.05	1.29	spn，中间的数字代表什么意思？看到你整理的字典中间就一个数字1.0

**Comment by GalaxieT** [comment]
抱歉刚看到

1. 这两个不同的映射是两个完全独立的系统，后者是MFA的作者专门设计的
2. mandarin_mfa.dict 中的数字涉及到这个音节前后停顿出现的概率，而我整理的字典中的数字对应这个拼音映射到相应音标的权重（轻声会有一个拼音到三种音标的映射）。这些格式都是MFA支持的字典格式，具体可以参考[MFA的说明文档](https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/dictionary.html)。
