### ISSUE TITLE
用这个字典，提示单词及其发音之间没有标签？

### ISSUE THREAD

**Issue by 4698to** [GalaxieT/MFA-mandarin-pinyin-dict-for-pretrained-mfa-model-v2.0#4]
Did not find any tabs, please ensure that your dictionary has tabs between words and their pronunciations.

**Comment by tuntun990606** [comment]
> 

请问您解决了吗?

**Comment by tuntun990606** [comment]
> Did not find any tabs, please ensure that your dictionary has tabs between words and their pronunciations.

请问您现在解决了吗

**Comment by GalaxieT** [comment]
mfa之后更新的版本要求字典的条目和音素之间用tab分开，已经修改。
