### ISSUE TITLE
某些拼音的mfa音素不正确并询问一些问题

### ISSUE THREAD

**Issue by CharlieLei** [GalaxieT/MFA-mandarin-pinyin-dict-for-pretrained-mfa-model-v2.0#5]
下面这些拼音对应的音素都错了：
- bao，gei，lia，mu，za，zao，zhuai
- le和lei弄反了
![image](https://user-images.githubusercontent.com/41474025/218725315-71a7465e-a734-4612-ad6e-4037070e6b50.png)

一些问题：
- 有单独一个n这个拼音吗？即使有n，n的音调似乎不是正确的
- 有单独一个r这个拼音吗？

**Comment by GalaxieT** [comment]
感谢纠错！抱歉afk了一段时间。
当时是以原字典中的汉字为中介对齐拼音和音素标记的，所以有些多音字就导致了这个问题。提出的几个错误都已经修正。
关于n和r：
n对应的是嗯，按字典是有n或ng两种标法，我将ng也更新进去了。
在mfa中，n只有一个音素符号ŋ̍˧˥，没有其他声调版本的音素符号，强行加进去的话可能会导致它报错。
r对应儿化，不对应单独的汉字，但在对齐中可能会用到，所以加了进来。
