### ISSUE TITLE
提醒一下用这个字典的同学，不要用Mandarin_mfa 3.0这个声学模型

### ISSUE THREAD

**Issue by Irislucent** [GalaxieT/MFA-mandarin-pinyin-dict-for-pretrained-mfa-model-v2.0#8]
感谢作者。用的时候踩到了奇怪的坑，MFA总是把我用空格分割好的拼音莫名其妙拆成字母部分和数字部分从而在字典里找不到对应。长时间搜索（MFA的文档真的太乱了）发现是Mandarin_mfa v3.0这个Acoustic model默认调用外部那个tokenizer再tokenize一遍你的transcript，而不是尊重已经提供好的transcript。对于拼音这个case，建议选择老版Acoustic model，也就是v2.0.

**Comment by GalaxieT** [comment]
感谢分享和提醒！
